### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by beck** [eligrey/classList.js#64]
This repo now has few more maintainers (including myself).

Before making any big changes would like to:

**Say Hi**

> hi

**Make a todo list**

1. [ ] Add some CI and browser testing
1. [ ] Fix https://github.com/eligrey/classList.js/issues/48
1. [ ] Publish a new version
1. [ ] Close my fork https://github.com/yola/classlist-polyfill/issues/9
1. [ ] Cleanup whitespace
1. [ ] Rewrite tests
1. [ ] Minify via npm `prepublish`
1. [ ] Start addressing open issues

**Flesh out any preferences**

When writing JS I generally stick to [airbnb](https://github.com/airbnb/javascript/tree/es5-deprecated/es5)-ish style.

Prefer Mocha+chai (with karma running the tests) instead of QUnit.

Prefer plain old shell/bash scripts instead task managers.

**Comment by stevenvachon** [comment]
I fixed #48 in the "Consolidated closures" commit in #53.

**Comment by beck** [comment]
@stevenvachon another preference is for single-purpose pull requests.

I agree with @eligrey about #53. IMO it does too much at once. Before the closures can be consolidated, lets cleanup the whitespace. Before we touch every line with whitespace cleanup, lets get the tests in working condition.  I would expect a fix for #48 to have a diff of ~2 lines, something like:

```diff
-}(self));
+}(typeof self !== 'undefined' ? self : this));
```

**Comment by stevenvachon** [comment]
The whitespace commit occurs before the closure consolidation commit.

**Comment by englishextra** [comment]
> -}(self));
+}(typeof self !== 'undefined' ? self : this));

This is what I do with every polyfill I deal with. 

BTW I'm gonna send a PR regarding !a===!b at the bottom of the polyfill, tha last thing which is a thorn.

**Comment by euwest** [comment]
@stevenvachon:

>another preference is for single-purpose pull requests.

>I agree ... about #53. IMO it does too much at once.

That's @beck responding to:

>I fixed #48 in the "Consolidated closures" commit in #53.
I fixed whitespace in the "Whitespace fixes" commit in #53.
I rewrote the tests in the "Improve tests" commit in #53.

He's telling you he would like those to be separate PRs, not just separate commits. Condescension is not an appropriate response.

**Comment by stevenvachon** [comment]
> He's telling you he would like those to be separate PRs, not just separate commits. Condescension is not an appropriate response.

And I'm telling him and anyone else that they can go through the commits. I have little interest in redoing my PRs after all this time.
